### ISSUE TITLE
SIGSEGV signal for Godot during terrain editing.

### ISSUE THREAD

**Issue by wojtekpil** [awkwardpolygons/awkpol1#1]
I I encountered a strange problem while editing the example terrain. Immediately after using the "Raise" tool, I switched to "Lower" mode and each time the effect is the same. I can edit the terrain for few seconds than it crashes.
I uploaded video of the problem: https://streamable.com/5aa7ix
 Here is a console output:
```
OpenGL ES 3.0 Renderer: GeForce GTX 1660 Ti/PCIe/SSE2
 
Mono: Logfile is: /home/wojtekpil/.local/share/godot/mono/mono_logs/2020_07_15 18.19.36 (14305).txt

=================================================================
	Native Crash Reporting
=================================================================
Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

=================================================================
	Native stacktrace:
=================================================================
	0xd20004 - /home/wojtekpil/Programs/Godot_3.2.2/Godot_v3.2.2-stable_mono_x11.64 : (null)
	0xd2037c - /home/wojtekpil/Programs/Godot_3.2.2/Godot_v3.2.2-stable_mono_x11.64 : (null)
	0xd12e28 - /home/wojtekpil/Programs/Godot_3.2.2/Godot_v3.2.2-stable_mono_x11.64 : (null)
	0xc8b691 - /home/wojtekpil/Programs/Godot_3.2.2/Godot_v3.2.2-stable_mono_x11.64 : (null)
	0x31e5d7c - /home/wojtekpil/Programs/Godot_3.2.2/Godot_v3.2.2-stable_mono_x11.64 : (null)
	0xaeedaf8 - Unknown

=================================================================
	Telemetry Dumper:
=================================================================
Pkilling 0x7f040d9fe700 from 0x7f04399acf80
Pkilling 0x7f0428817700 from 0x7f04399acf80
* Assertion: should not be reached at threads.c:6258
Entering thread summarizer pause from 0x7f04399acf80
Finished thread summarizer pause from 0x7f04399acf80.

Waiting for dumping threads to resume

=================================================================
	External Debugger Dump:
=================================================================
[New LWP 14306]
[New LWP 14316]
[New LWP 14317]
[New LWP 14318]
[New LWP 14319]
[New LWP 14320]
[New LWP 14321]
[New LWP 14323]
[New LWP 14325]
[New LWP 14326]
[New LWP 14328]
[New LWP 14329]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
0x00007f04395b024a in __waitpid (pid=pid@entry=14350, stat_loc=stat_loc@entry=0x7fff0092dd44, options=options@entry=0) at ../sysdeps/unix/sysv/linux/waitpid.c:30
30	../sysdeps/unix/sysv/linux/waitpid.c: No such file or directory.
  Id   Target Id         Frame 
* 1    Thread 0x7f04399acf80 (LWP 14305) "Godot_v3.2.2-st" 0x00007f04395b024a in __waitpid (pid=pid@entry=14350, stat_loc=stat_loc@entry=0x7fff0092dd44, options=options@entry=0) at ../sysdeps/unix/sysv/linux/waitpid.c:30
  2    Thread 0x7f04399ab700 (LWP 14306) "Godot_v3.2.2-st" 0x00007f04395ae6e6 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=0, futex_word=0x5a60938) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
  3    Thread 0x7f043077d700 (LWP 14316) "Godot_v3.2.2-st" 0x00007f04395ae6e6 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=0, futex_word=0x5e0ca98) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
  4    Thread 0x7f042897a700 (LWP 14317) "Godot_v3.2.2-st" 0x00007f04395afc70 in __GI___nanosleep (requested_time=0x7f0428979d50, remaining=0x7f0428979d50) at ../sysdeps/unix/sysv/linux/nanosleep.c:28
  5    Thread 0x7f0428939700 (LWP 14318) "Godot_v3.2.2-st" 0x00007f0438ae7a30 in __GI___nanosleep (requested_time=requested_time@entry=0x7f0428938d20, remaining=remaining@entry=0x0) at ../sysdeps/unix/sysv/linux/nanosleep.c:28
  6    Thread 0x7f040f7ff700 (LWP 14319) "SGen worker" 0x00007f04395ab9f3 in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x4c8af88 <work_cond+40>) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
  7    Thread 0x7f0428817700 (LWP 14320) "Finalizer" 0x00007f04395ae6e6 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=0, futex_word=0x4c78720 <finalizer_sem>) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
  8    Thread 0x7f0431467700 (LWP 14321) "Godot_v3.2.2-st" 0x00007f04395afc70 in __GI___nanosleep (requested_time=0x7f0431466b90, remaining=0x7f0431466b90) at ../sysdeps/unix/sysv/linux/nanosleep.c:28
  9    Thread 0x7f0431426700 (LWP 14323) "Godot_v3.2.2-st" 0x00007f04395afc70 in __GI___nanosleep (requested_time=0x7f0431425d80, remaining=0x7f0431425d80) at ../sysdeps/unix/sysv/linux/nanosleep.c:28
  10   Thread 0x7f04313e5700 (LWP 14325) "Godot_v3.2.2-st" 0x00007f04395afc70 in __GI___nanosleep (requested_time=0x7f04313e4d40, remaining=0x7f04313e4d40) at ../sysdeps/unix/sysv/linux/nanosleep.c:28
  11   Thread 0x7f040d9fe700 (LWP 14326) "Thread Pool I/O" 0x00007f0438b17cf9 in __GI___poll (fds=0xb6ca590, nfds=2, timeout=timeout@entry=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
  12   Thread 0x7f04300ba700 (LWP 14328) "Godot_v3.2.2-st" 0x00007f04395ae6e6 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=0, futex_word=0xd052e08) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
  13   Thread 0x7f0430079700 (LWP 14329) "worker" 0x00007f04395ae6e6 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=0, futex_word=0x24797a48) at ../sysdeps/unix/sysv/linux/futex-internal.h:205

Thread 13 (Thread 0x7f0430079700 (LWP 14329)):
#0  0x00007f04395ae6e6 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=0, futex_word=0x24797a48) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
#1  do_futex_wait (sem=sem@entry=0x24797a48, abstime=0x0) at sem_waitcommon.c:111
#2  0x00007f04395ae7d8 in __new_sem_wait_slow (sem=0x24797a48, abstime=0x0) at sem_waitcommon.c:181
#3  0x000000000299d42d in SemaphorePosix::wait() [clone .part.0] ()
#4  0x00007f04300781f0 in ?? ()
#5  0x0000000003102d61 in MethodBind0R<Error>::call(Object*, Variant const**, int, Variant::CallError&) ()
#6  0x00000000012ce88a in ClassDB::get_method(StringName, StringName) ()
#7  0x000000000aeed950 in ?? ()
#8  0x3b90932b41686600 in ?? ()
#9  0x00000000247701c0 in ?? ()
#10 0x00007f04300781f0 in ?? ()
#11 0x00000000247701c0 in ?? ()
#12 0x0000000001252793 in Object::call(StringName const&, Variant const**, int, Variant::CallError&) ()
#13 0x00007f0430078200 in ?? ()
#14 0x00007f0430078348 in ?? ()
#15 0x00007f04300781c0 in ?? ()
#16 0x00007f04300781f0 in ?? ()
#17 0x0000000000000000 in ?? ()

Thread 12 (Thread 0x7f04300ba700 (LWP 14328)):
#0  0x00007f04395ae6e6 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=0, futex_word=0xd052e08) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
#1  do_futex_wait (sem=sem@entry=0xd052e08, abstime=0x0) at sem_waitcommon.c:111
#2  0x00007f04395ae7d8 in __new_sem_wait_slow (sem=0xd052e08, abstime=0x0) at sem_waitcommon.c:181
#3  0x000000000299d42d in SemaphorePosix::wait() [clone .part.0] ()
#4  0x000000000d0307e0 in ?? ()
#5  0x0000000002705323 in EditorResourcePreview::_thread() ()
#6  0x0000000002a86da5 in ThreadPosix::thread_callback(void*) ()
#7  0x0000000000000000 in ?? ()

Thread 11 (Thread 0x7f040d9fe700 (LWP 14326)):
#0  0x00007f0438b17cf9 in __GI___poll (fds=0xb6ca590, nfds=2, timeout=timeout@entry=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x0000000000f2db57 in poll (__timeout=__timeout@entry=-1, __nfds=<optimized out>, __fds=<optimized out>) at /usr/include/x86_64-linux-gnu/bits/poll2.h:46
#2  mono_poll (ufds=<optimized out>, nfds=<optimized out>, timeout=timeout@entry=-1) at mono-poll.c:45
#3  0x0000000000e9cbd7 in poll_event_wait (callback=0xe9d430 <wait_callback>, user_data=0x7f03e4002480) at threadpool-io-poll.c:153
#4  0x0000000000e9dffa in selector_thread (data=data@entry=0x0) at threadpool-io.c:457
#5  0x0000000000eb0ed5 in start_wrapper_internal (stack_ptr=0x7f040d9ff000, start_info=0x0) at threads.c:1226
#6  start_wrapper (data=0xb6d0bf0) at threads.c:1299
#7  0x00007f04395a56db in start_thread (arg=0x7f040d9fe700) at pthread_create.c:463
#8  0x00007f0438b24a3f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 10 (Thread 0x7f04313e5700 (LWP 14325)):
#0  0x00007f04395afc70 in __GI___nanosleep (requested_time=0x7f04313e4d40, remaining=0x7f04313e4d40) at ../sysdeps/unix/sysv/linux/nanosleep.c:28
#1  0x0000000000f8350b in OS_Unix::delay_usec(unsigned int) const [clone .constprop.12990] ()
#2  0x0000000000000000 in ?? ()

Thread 9 (Thread 0x7f0431426700 (LWP 14323)):
#0  0x00007f04395afc70 in __GI___nanosleep (requested_time=0x7f0431425d80, remaining=0x7f0431425d80) at ../sysdeps/unix/sysv/linux/nanosleep.c:28
#1  0x0000000000f8350b in OS_Unix::delay_usec(unsigned int) const [clone .constprop.12990] ()
#2  0x0000000000000000 in ?? ()

Thread 8 (Thread 0x7f0431467700 (LWP 14321)):
#0  0x00007f04395afc70 in __GI___nanosleep (requested_time=0x7f0431466b90, remaining=0x7f0431466b90) at ../sysdeps/unix/sysv/linux/nanosleep.c:28
#1  0x0000000000f8350b in OS_Unix::delay_usec(unsigned int) const [clone .constprop.12990] ()
#2  0x0000000000000000 in ?? ()

Thread 7 (Thread 0x7f0428817700 (LWP 14320)):
#0  0x00007f04395ae6e6 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=0, futex_word=0x4c78720 <finalizer_sem>) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
#1  do_futex_wait (sem=sem@entry=0x4c78720 <finalizer_sem>, abstime=0x0) at sem_waitcommon.c:111
#2  0x00007f04395ae7d8 in __new_sem_wait_slow (sem=sem@entry=0x4c78720 <finalizer_sem>, abstime=0x0) at sem_waitcommon.c:181
#3  0x00007f04395ae849 in __new_sem_wait (sem=sem@entry=0x4c78720 <finalizer_sem>) at sem_wait.c:42
#4  0x0000000000ddd1f8 in mono_os_sem_wait (flags=MONO_SEM_FLAGS_ALERTABLE, sem=0x4c78720 <finalizer_sem>) at ../../mono/utils/mono-os-semaphore.h:203
#5  mono_coop_sem_wait (flags=MONO_SEM_FLAGS_ALERTABLE, sem=0x4c78720 <finalizer_sem>) at ../../mono/utils/mono-coop-semaphore.h:41
#6  finalizer_thread (unused=unused@entry=0x0) at gc.c:967
#7  0x0000000000eb0ed5 in start_wrapper_internal (stack_ptr=0x7f0428818000, start_info=0x0) at threads.c:1226
#8  start_wrapper (data=0x7146870) at threads.c:1299
#9  0x00007f04395a56db in start_thread (arg=0x7f0428817700) at pthread_create.c:463
#10 0x00007f0438b24a3f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 6 (Thread 0x7f040f7ff700 (LWP 14319)):
#0  0x00007f04395ab9f3 in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x4c8af88 <work_cond+40>) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
#1  __pthread_cond_wait_common (abstime=0x0, mutex=0x4c8afa0 <lock>, cond=0x4c8af60 <work_cond>) at pthread_cond_wait.c:502
#2  __pthread_cond_wait (cond=cond@entry=0x4c8af60 <work_cond>, mutex=mutex@entry=0x4c8afa0 <lock>) at pthread_cond_wait.c:655
#3  0x0000000000f1b9d6 in mono_os_cond_wait (mutex=0x4c8afa0 <lock>, cond=0x4c8af60 <work_cond>) at ../../mono/utils/mono-os-mutex.h:177
#4  get_work (job=<synthetic pointer>, do_idle=<synthetic pointer>, work_context=<synthetic pointer>, worker_index=0) at sgen-thread-pool.c:165
#5  thread_func (data=<optimized out>) at sgen-thread-pool.c:196
#6  0x00007f04395a56db in start_thread (arg=0x7f040f7ff700) at pthread_create.c:463
#7  0x00007f0438b24a3f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 5 (Thread 0x7f0428939700 (LWP 14318)):
#0  0x00007f0438ae7a30 in __GI___nanosleep (requested_time=requested_time@entry=0x7f0428938d20, remaining=remaining@entry=0x0) at ../sysdeps/unix/sysv/linux/nanosleep.c:28
#1  0x00007f0438b1a977 in usleep (useconds=<optimized out>) at ../sysdeps/posix/usleep.c:32
#2  0x000000000323ec02 in JoypadLinux::monitor_joypads() ()
#3  0x0000005b0000006e in ?? ()
#4  0x0000000006932680 in ?? ()
#5  0xffffffffffffff48 in ?? ()
#6  0x00007f0400000b50 in ?? ()
#7  0x706e692f7665642f in ?? ()
#8  0x746e6576652f7475 in ?? ()
#9  0x0000000000003133 in ?? ()
#10 0x000000000692aea0 in ?? ()
#11 0x000000000692aeb0 in ?? ()
#12 0x00007f0438a9a35d in __GI___libc_malloc (bytes=32) at malloc.c:3065
#13 0x00007f0428938ec0 in ?? ()
#14 0x0000000000000000 in ?? ()

Thread 4 (Thread 0x7f042897a700 (LWP 14317)):
#0  0x00007f04395afc70 in __GI___nanosleep (requested_time=0x7f0428979d50, remaining=0x7f0428979d50) at ../sysdeps/unix/sysv/linux/nanosleep.c:28
#1  0x0000000000f8350b in OS_Unix::delay_usec(unsigned int) const [clone .constprop.12990] ()
#2  0x0000000000000000 in ?? ()

Thread 3 (Thread 0x7f043077d700 (LWP 14316)):
#0  0x00007f04395ae6e6 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=0, futex_word=0x5e0ca98) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
#1  do_futex_wait (sem=sem@entry=0x5e0ca98, abstime=0x0) at sem_waitcommon.c:111
#2  0x00007f04395ae7d8 in __new_sem_wait_slow (sem=0x5e0ca98, abstime=0x0) at sem_waitcommon.c:181
#3  0x000000000299d42d in SemaphorePosix::wait() [clone .part.0] ()
#4  0x00007f043077e020 in ?? ()
#5  0x000000000160ff23 in VisualServerScene::_gi_probe_bake_thread() ()
#6  0x0000000000000000 in ?? ()

Thread 2 (Thread 0x7f04399ab700 (LWP 14306)):
#0  0x00007f04395ae6e6 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=0, futex_word=0x5a60938) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
#1  do_futex_wait (sem=sem@entry=0x5a60938, abstime=0x0) at sem_waitcommon.c:111
#2  0x00007f04395ae7d8 in __new_sem_wait_slow (sem=0x5a60938, abstime=0x0) at sem_waitcommon.c:181
#3  0x000000000299d42d in SemaphorePosix::wait() [clone .part.0] ()
#4  0x0000000005a60970 in ?? ()
#5  0x00000000010e1ec4 in _IP_ResolverPrivate::_thread_function(void*) ()
#6  0x0000000005a60980 in ?? ()
#7  0x00007f0438a9a35d in __GI___libc_malloc (bytes=94767416) at malloc.c:3065
#8  0x00007f04399aaec0 in ?? ()
#9  0x0000000000000000 in ?? ()

Thread 1 (Thread 0x7f04399acf80 (LWP 14305)):
#0  0x00007f04395b024a in __waitpid (pid=pid@entry=14350, stat_loc=stat_loc@entry=0x7fff0092dd44, options=options@entry=0) at ../sysdeps/unix/sysv/linux/waitpid.c:30
#1  0x0000000000d201f1 in dump_native_stacktrace (mctx=mctx@entry=0x7fff0092e880, signal=0x33dc227 "SIGSEGV") at mini-posix.c:1089
#2  0x0000000000d2037c in mono_dump_native_crash_info (signal=signal@entry=0x33dc227 "SIGSEGV", mctx=mctx@entry=0x7fff0092e880, info=info@entry=0x0) at mini-posix.c:1135
#3  0x0000000000d12e28 in mono_handle_native_crash (signal=signal@entry=0x33dc227 "SIGSEGV", mctx=mctx@entry=0x7fff0092e880, info=info@entry=0x0) at mini-exceptions.c:3423
#4  0x0000000000c8b691 in altstack_handle_and_restore () at exceptions-amd64.c:875
#5  0x00000000031e5d7c in PoolVector<unsigned char>::_copy_on_write() ()
#6  0x0000000000000000 in ?? ()

=================================================================
	Basic Fault Address Reporting
=================================================================
Memory around native instruction pointer (0x31e5d7c):0x31e5d6c  1f 44 00 00 f0 41 83 06 01 48 8b 03 49 8b 75 08  .D...A...H..I.u.
0x31e5d7c  48 8b 40 18 89 c1 85 c0 0f 8e 65 01 00 00 31 ff  H.@.......e...1.
0x31e5d8c  e9 30 ff ff ff 66 66 66 66 66 66 2e 0f 1f 84 00  .0...ffffff.....
0x31e5d9c  00 00 00 00 ff d0 e9 d6 fe ff ff 66 0f 1f 84 00  ...........f....

=================================================================
	Managed Stacktrace:
=================================================================
=================================================================
```

**Comment by arccoza** [comment]
Is this Godot 3.2.2 (I'm still working on 3.2.1)? Are you running the example directly or inside another project?

**Comment by wojtekpil** [comment]
Yes, this is 3.2.2. I am running it directly. I just cloned the repo and imported it to Godot.

**Comment by arccoza** [comment]
I updated to 3.2.2, and it worked fine. Then I switched to the C Sharp / Mono build, which you're using, and got the same SIGSEGV crash. So this is definitely a problem with the unstable Mono build. And I'm pretty sure it's got to do with the thread I'm using for the ray picker. If you try just painting, instead of sculpting, it works fine because the ray picker only has to grab the heightmap once, unlike when sculpting.

Since I intend to replace the current ray picker with a better implementation, this problem should disappear then.
In the meantime you can use the standard Godot build.

**Comment by arccoza** [comment]
I've updated the terrain ray picker with a GPU implementation, and removed the old threaded version. Feels much smoother, and testing under the mono build there are no crashes. Give it a test and let me know.

**Comment by wojtekpil** [comment]
I tested it and it works much better with the new ray picker. SIGSEG is no longer present, so I'm closing the issue.
